### ISSUE TITLE
关于房屋历史记录的问题

### ISSUE THREAD

**Issue by wincoral** [nyaoouo/WanaHomeWeb#10]
希望能把历史记录里的前持有人记录关闭，数据库里也最好不要保存玩家id和部队名，这个是没有必要的数据吧，房主改名后历史记录里也会显示，这个侵犯玩家隐私了，fflogs都能申请隐藏自己的id，不经过别人的同意上传id我认为不太妥当，望回复，谢谢！

**Comment by nyaoouo** [comment]
`隐私，顾名思义，隐蔽、不公开的私事。在汉语中，“隐”字的主要含义是隐避、隐藏，《荀子·王制》：“故近者不隐其能，远者不疾其劳。”引申为不公开之意。`
来自 [百度百科](https://baike.baidu.com/item/%E9%9A%90%E7%A7%81/12883) 
作为一个在游戏里面公开可以获取的信息的记录，您可以先向SE申请大水晶处可以显示为匿名呢，到时候我这边将会考虑跟进相关机制的呢（）
